# Azure DevOps Pipeline for Trading Pro Deployment
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'your-azure-subscription'
  appName: 'trading-pro-app'
  resourceGroupName: 'trading-pro-rg'
  location: 'East US'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
        displayName: 'Use Python 3.11'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python manage.py check --settings=trading_project.settings_production
        python manage.py collectstatic --noinput --settings=trading_project.settings_production
      displayName: 'Django checks and collect static'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(appName)'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              appSettings: |
                -SECRET_KEY "$(SECRET_KEY)"
                -DEBUG "False"
                -DATABASE_URL "$(DATABASE_URL)"
                -OPENAI_API_KEY "$(OPENAI_API_KEY)"
                -IB_HOST "$(IB_HOST)"
                -IB_PORT "$(IB_PORT)"
                -IB_CLIENT_ID "$(IB_CLIENT_ID)"
                -EMAIL_HOST "$(EMAIL_HOST)"
                -EMAIL_PORT "$(EMAIL_PORT)"
                -EMAIL_HOST_USER "$(EMAIL_HOST_USER)"
                -EMAIL_HOST_PASSWORD "$(EMAIL_HOST_PASSWORD)"
                -REDIS_URL "$(REDIS_URL)"
                -AZURE_STORAGE_ACCOUNT_NAME "$(AZURE_STORAGE_ACCOUNT_NAME)"
                -AZURE_STORAGE_ACCOUNT_KEY "$(AZURE_STORAGE_ACCOUNT_KEY)"
                -AZURE_STORAGE_CONTAINER "$(AZURE_STORAGE_CONTAINER)"
