# Generated by Django 5.2 on 2025-08-29 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20, null=True)),
                ('sentiment_confidence', models.FloatField(blank=True, null=True)),
                ('sentiment_reason', models.TextField(blank=True, null=True)),
                ('impact_score', models.FloatField(blank=True, null=True)),
                ('impact_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True)),
                ('impact_confidence', models.FloatField(blank=True, null=True)),
                ('affected_sectors', models.JSONField(blank=True, default=list)),
                ('affected_companies', models.JSONField(blank=True, default=list)),
                ('trading_implications', models.TextField(blank=True, null=True)),
                ('potential_moves', models.JSONField(blank=True, default=list)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'News Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='TradingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10)),
                ('confidence', models.FloatField(help_text='Confidence score from 0.0 to 1.0')),
                ('reason', models.TextField(help_text='Reasoning for the recommendation')),
                ('timeframe', models.CharField(choices=[('short', 'Short Term (1-7 days)'), ('medium', 'Medium Term (1-4 weeks)'), ('long', 'Long Term (1-12 months)')], max_length=10)),
                ('gpt_model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='apiconfig',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='scrapingsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='main_app_ne_categor_c376ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='main_app_ne_scraped_bc6aa0_idx',
        ),
        migrations.RemoveField(
            model_name='apiconfig',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='apiconfig',
            name='rate_limit',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_active',
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_impact',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_impact_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_model_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_sentiment_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gpt_sentiment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(choices=[('reuters', 'Reuters'), ('bloomberg', 'Bloomberg'), ('yahoo_finance', 'Yahoo Finance'), ('marketwatch', 'MarketWatch'), ('cnbc', 'CNBC'), ('finnhub', 'FinnHub API'), ('manual', 'Manual Entry')], default='reuters', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapingsession',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapingsession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['gpt_sentiment', 'gpt_impact'], name='main_app_ne_gpt_sen_af568f_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category', 'tags'], name='main_app_ne_categor_73c361_idx'),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='main_app.newsarticle'),
        ),
        migrations.AddField(
            model_name='tradingrecommendation',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='trading_recommendations', to='main_app.newsarticle'),
        ),
        migrations.AddField(
            model_name='tradingrecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tradingrecommendation',
            index=models.Index(fields=['ticker', 'action'], name='main_app_tr_ticker_9acfed_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingrecommendation',
            index=models.Index(fields=['confidence', 'timeframe'], name='main_app_tr_confide_0c1166_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingrecommendation',
            index=models.Index(fields=['analysis_date'], name='main_app_tr_analysi_1b1c7b_idx'),
        ),
    ]
