# Generated by Django 5.2 on 2025-09-01 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ibconnection_datacollectionjob_marketticker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('strong_buy', 'Strong Buy'), ('strong_sell', 'Strong Sell')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score from 0.0 to 1.0')),
                ('source', models.CharField(choices=[('gpt_analysis', 'GPT Analysis'), ('market_data', 'Market Data'), ('combined', 'Combined Analysis'), ('technical', 'Technical Analysis'), ('sentiment', 'Sentiment Analysis')], default='combined', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('executed', 'Executed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('market_data_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('combined_score', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(help_text='Detailed reasoning for the signal')),
                ('market_context', models.JSONField(blank=True, default=dict)),
                ('risk_assessment', models.TextField(blank=True, null=True)),
                ('execution_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('execution_time', models.DateTimeField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('related_articles', models.ManyToManyField(blank=True, related_name='signals', to='main_app.newsarticle')),
                ('related_market_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='main_app.marketdata')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='main_app.marketticker')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SignalMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_volatility', models.FloatField(blank=True, null=True)),
                ('market_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('sector_performance', models.JSONField(blank=True, default=dict)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('moving_average_20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moving_average_50', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bollinger_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bollinger_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_ratio', models.FloatField(blank=True, null=True)),
                ('average_volume', models.BigIntegerField(blank=True, null=True)),
                ('news_sentiment_score', models.FloatField(blank=True, null=True)),
                ('news_impact_score', models.FloatField(blank=True, null=True)),
                ('recent_news_count', models.IntegerField(default=0)),
                ('market_cap_category', models.CharField(blank=True, max_length=20, null=True)),
                ('sector_rank', models.IntegerField(blank=True, null=True)),
                ('peer_performance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='main_app.tradingsignal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['ticker', 'signal_type'], name='main_app_tr_ticker__7e1690_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['confidence', 'timestamp'], name='main_app_tr_confide_c16acf_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['status', 'timestamp'], name='main_app_tr_status_0e2fae_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingsignal',
            index=models.Index(fields=['source', 'timestamp'], name='main_app_tr_source_0dfd88_idx'),
        ),
    ]
