# Generated by Django 5.2 on 2025-09-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tradingsignal_signalmetadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the external system/company', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the subscriber')),
                ('contact_email', models.EmailField(help_text='Contact email for the subscriber', max_length=254)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for real-time signal delivery')),
                ('api_key', models.CharField(help_text='API key for authentication', max_length=64, unique=True)),
                ('secret_key', models.CharField(help_text='Secret key for webhook authentication', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000, help_text='Maximum requests per hour')),
                ('subscribed_tickers', models.JSONField(default=list, help_text='List of ticker symbols to receive signals for')),
                ('min_confidence_threshold', models.DecimalField(decimal_places=2, default=0.5, help_text='Minimum confidence threshold for signals', max_digits=3)),
                ('signal_types', models.JSONField(default=list, help_text='Types of signals to receive (buy, sell, hold)')),
            ],
            options={
                'verbose_name': 'API Subscriber',
                'verbose_name_plural': 'API Subscribers',
                'db_table': 'api_subscribers',
            },
        ),
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('signal', 'Signal Request'), ('webhook', 'Webhook Delivery'), ('auth', 'Authentication'), ('rate_limit', 'Rate Limit Exceeded')], max_length=20)),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField()),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='main_app.apisubscriber')),
            ],
            options={
                'verbose_name': 'API Access Log',
                'verbose_name_plural': 'API Access Logs',
                'db_table': 'api_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SignalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('webhook', 'Webhook'), ('polling', 'Polling')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='main_app.tradingsignal')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_deliveries', to='main_app.apisubscriber')),
            ],
            options={
                'verbose_name': 'Signal Delivery',
                'verbose_name_plural': 'Signal Deliveries',
                'db_table': 'signal_deliveries',
                'unique_together': {('signal', 'subscriber')},
            },
        ),
    ]
